repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        types: [python]
        pass_filenames: true
        files: \.py$
        verbose: true
        stages: [commit]
      - id: ruff-check-fix
        name: ruff check and fix
        entry: ruff check . --fix
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
        stages: [commit]
      - id: ruff-format
        name: ruff format
        entry: ruff format .
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
        stages: [commit]
      - id: autoflake
        name: autoflake
        entry: autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place . --exclude=__init__.py
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
        stages: [commit]
      - id: black
        name: black
        entry: black .
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
        stages: [commit]
      - id: isort
        name: isort
        entry: isort .
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
        stages: [commit]
      - id: isort-force-single-line
        name: isort force single line
        entry: isort --force-single-line-imports .
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
        stages: [commit]

  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.71.0
    hooks:
      - id: cfn-lint
        files: cfn/.*\.(json|yml|yaml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
