# ローカルで起動するためのdocker-composeファイルです
# pythonファイルを更新すると自動で反映されるようになっています
version: '3'
services:
  event-matching-service:
    build:
      dockerfile: Dockerfile # Dockerfileのディレクトリを指定します
    command:
      bash -c './scripts/reset_db.sh &&
      python manage.py runserver 0.0.0.0:8000'
    volumes:
      - '.:/app'
    ports:
      - "8000:8000" # 左側が外部からのアクセス時のポート番号:右側がdockerコンテナからアクセスする時のポート番号。ホストの8000番からコンテナの8000番へポートフォワードしています
    # コンテナ名
    container_name: event-matching-service
    tty: true # ポート待受とかしていないコンテナの場合、trueに設定しておくとコンテナが起動し続けます
    working_dir: '/app'
    env_file:
      - .env
