# Generated by Django 5.0.4 on 2024-04-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
