# Generated by Django 5.0.4 on 2024-04-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizerprofile_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role_name',
        ),
    ]
