# Generated by Django 5.0.4 on 2024-04-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
