name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      EMAIL_HOST: "dummy@gmail.com"
      EMAIL_HOST_USER: "dummy_user@gmail.com"
      EMAIL_HOST_PASSWORD: "dummy password"
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
      
    - name: Start Django server
      run: |
        python manage.py runserver &
        sleep 5  # Wait for server to start

    - name: curl
      run: |
        curl http://127.0.0.1:8000/events/list
        
    - name: Run your tests
      run: |
        pytest 
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: .pytest-results/
